import 'dart:math' as math;

class FanficBlindBoxInspiration {
  const FanficBlindBoxInspiration(this.number, this.inspiration);

  final int number;
  final String inspiration;

  String get label => '#$number $inspiration';
}

const List<FanficBlindBoxInspiration> fanficBlindBoxInspirations =
    <FanficBlindBoxInspiration>[
  FanficBlindBoxInspiration(1, '原作向if线'),
  FanficBlindBoxInspiration(2, '吸血鬼pa'),
  FanficBlindBoxInspiration(3, '摩登都市pa'),
  FanficBlindBoxInspiration(4, '花吐症pa'),
  FanficBlindBoxInspiration(5, '末世pa'),
  FanficBlindBoxInspiration(6, '霍格沃兹pa'),
  FanficBlindBoxInspiration(7, '古风pa'),
  FanficBlindBoxInspiration(8, '西欧pa'),
  FanficBlindBoxInspiration(9, '中恐pa'),
  FanficBlindBoxInspiration(10, '修仙pa'),
  FanficBlindBoxInspiration(11, '西幻pa'),
  FanficBlindBoxInspiration(12, '变小'),
  FanficBlindBoxInspiration(13, '魔女pa'),
  FanficBlindBoxInspiration(14, '出租屋文学'),
  FanficBlindBoxInspiration(15, '学生时代'),
  FanficBlindBoxInspiration(16, '不doi就出不去的房间'),
  FanficBlindBoxInspiration(17, '公路pa'),
  FanficBlindBoxInspiration(18, '赛车pa'),
  FanficBlindBoxInspiration(19, '无限流pa'),
  FanficBlindBoxInspiration(20, '乐队pa'),
  FanficBlindBoxInspiration(21, '职场pa'),
  FanficBlindBoxInspiration(22, '君臣pa'),
  FanficBlindBoxInspiration(23, '哨向'),
  FanficBlindBoxInspiration(24, 'abo'),
  FanficBlindBoxInspiration(25, '警员pa'),
  FanficBlindBoxInspiration(26, '娱乐圈pa'),
  FanficBlindBoxInspiration(27, '师徒pa'),
  FanficBlindBoxInspiration(28, '骨科pa'),
  FanficBlindBoxInspiration(29, '捡手机'),
  FanficBlindBoxInspiration(30, '回到幼时pa'),
  FanficBlindBoxInspiration(31, '失忆后一见钟情'),
  FanficBlindBoxInspiration(32, '吃醋'),
  FanficBlindBoxInspiration(33, '9号房间'),
  FanficBlindBoxInspiration(34, '相性一百问'),
  FanficBlindBoxInspiration(35, 'SM'),
  FanficBlindBoxInspiration(36, '主仆pa'),
  FanficBlindBoxInspiration(37, '权谋pa'),
  FanficBlindBoxInspiration(38, '单性转'),
  FanficBlindBoxInspiration(39, '双性转'),
  FanficBlindBoxInspiration(40, '论坛体'),
  FanficBlindBoxInspiration(41, 'G向'),
  FanficBlindBoxInspiration(42, '养成pa'),
  FanficBlindBoxInspiration(43, '乡村pa'),
  FanficBlindBoxInspiration(44, '现代pa'),
  FanficBlindBoxInspiration(45, '童话pa'),
  FanficBlindBoxInspiration(46, '西部pa'),
  FanficBlindBoxInspiration(47, '日常'),
  FanficBlindBoxInspiration(48, '同居'),
  FanficBlindBoxInspiration(49, '异地pa'),
  FanficBlindBoxInspiration(50, '女仆装'),
  FanficBlindBoxInspiration(51, '黑道pa'),
  FanficBlindBoxInspiration(52, '医患pa'),
  FanficBlindBoxInspiration(53, '赛博朋克pa'),
  FanficBlindBoxInspiration(54, 'cake&fork'),
  FanficBlindBoxInspiration(55, '动物塑'),
  FanficBlindBoxInspiration(56, '食物塑'),
  FanficBlindBoxInspiration(57, '兽耳'),
  FanficBlindBoxInspiration(58, '破镜重圆'),
  FanficBlindBoxInspiration(59, '老夫老妻'),
  FanficBlindBoxInspiration(60, '相爱相杀'),
  FanficBlindBoxInspiration(61, '狗仔与明星pa'),
  FanficBlindBoxInspiration(62, '共感娃娃'),
  FanficBlindBoxInspiration(63, '灵魂互换'),
  FanficBlindBoxInspiration(64, '杀青梗'),
  FanficBlindBoxInspiration(65, '观影体'),
  FanficBlindBoxInspiration(66, '发烧'),
  FanficBlindBoxInspiration(67, '醉酒'),
  FanficBlindBoxInspiration(68, '采访'),
  FanficBlindBoxInspiration(69, '恨海情天'),
  FanficBlindBoxInspiration(70, '史密斯夫妇'),
  FanficBlindBoxInspiration(71, '轮回梗'),
  FanficBlindBoxInspiration(72, '三人行修罗场'),
  FanficBlindBoxInspiration(73, '变猫/狗'),
  FanficBlindBoxInspiration(74, '先婚后爱'),
  FanficBlindBoxInspiration(75, '事后'),
  FanficBlindBoxInspiration(76, '青梅竹马'),
  FanficBlindBoxInspiration(77, '县城文学'),
  FanficBlindBoxInspiration(78, '幼稚园'),
  FanficBlindBoxInspiration(79, '民国pa'),
  FanficBlindBoxInspiration(80, '神话pa'),
  FanficBlindBoxInspiration(81, '误会'),
  FanficBlindBoxInspiration(82, '失忆'),
  FanficBlindBoxInspiration(83, '穿越'),
  FanficBlindBoxInspiration(84, '人外'),
  FanficBlindBoxInspiration(85, '实验室pa'),
  FanficBlindBoxInspiration(86, '26字母'),
  FanficBlindBoxInspiration(87, '阴阳两隔'),
  FanficBlindBoxInspiration(88, '丧尸pa'),
  FanficBlindBoxInspiration(89, '结婚'),
  FanficBlindBoxInspiration(90, '生长痛'),
  FanficBlindBoxInspiration(91, '炮友pa'),
  FanficBlindBoxInspiration(92, '神明&神父'),
  FanficBlindBoxInspiration(93, '教会pa'),
  FanficBlindBoxInspiration(94, '吐真剂'),
  FanficBlindBoxInspiration(95, '寿命论'),
  FanficBlindBoxInspiration(96, '狐狸窗'),
  FanficBlindBoxInspiration(97, '灵魂伴侣pa'),
  FanficBlindBoxInspiration(98, '暗恋pa'),
  FanficBlindBoxInspiration(99, '楚门的世界pa'),
];

FanficBlindBoxInspiration rollFanficBlindBoxInspiration({
  math.Random? random,
}) {
  final source = random ?? math.Random();
  return fanficBlindBoxInspirations[
      source.nextInt(fanficBlindBoxInspirations.length)];
}
